#!/usr/bin/env python3

from subprocess import run
from os import geteuid, symlink, path

def main():
    # We require root permissions to copy into /usr/bin
    if geteuid() != 0:
        exit("Root priviledges required to symlink into /usr/bin. Rerun with 'sudo'.")

    # Symlink certain scripts to /usr/bin
    dir = path.dirname(__file__)
    symlink(f'{dir}/volume-up', '/usr/bin/volume-up')
    symlink(f'{dir}/volume-down', '/usr/bin/volume-down')
    symlink(f'{dir}/setup-displays', '/usr/bin/setup-displays')
    symlink(f'{dir}/setup-sound', '/usr/bin/setup-sound')

if __name__ == "__main__":
    main()

